version: "3.4"

services:
  app:
    image: maven:3-jdk-8-alpine
    network_mode: host
    env_file:
      - .env
    environment:
      MAVEN_CONFIG: /var/maven/.m2
      MAVEN_OPTS: -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9000
    entrypoint: >
      mvn
        -Duser.home=/var/maven
        -Dmaven.tomcat.port=9001
        tomcat:run
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/.m2/:/var/maven/.m2
      - ./:/code
    working_dir: /code
    tty: true
