# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3.4"

services:
  app:
    image: maven:3-openjdk-17-slim
    environment:
      MAVEN_CONFIG: /var/maven/.m2
      MAVEN_OPTS: -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9000"
    command: >
      mvn
      -Duser.home=/var/maven
      clean
      compile
      spring-boot:run
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ~/.m2/:/var/maven/.m2
      - ./:/code
    working_dir: /code
    tty: true
    network_mode: host
