name: CI/CD bike-boxes

on:
  push:
    paths:
      - "data-collectors/bike-boxes/**"
      - ".github/workflows/ci-bike-boxes.yml"

env:
  WORKING_DIRECTORY: data-collectors/bike-boxes
  PROJECT_NAME: odh-mobility-dc-bike-boxes
  DOCKER_IMAGE: ghcr.io/${{ github.repository }}/odh-mobility-dc-bike-boxes
  DOCKER_TAG: ${{ github.sha }}
  JAVA_VERSION: '17'
  ODH_ORIGIN: bicincitta
  ODH_PERIOD: 600
  ODH_STATIONTYPE: BikeParking
  ODH_STATIONBAYTYPE: BikeParkingBay

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Test code
        uses: noi-techpark/github-actions/maven-test@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          working-directory: ${{ env.WORKING_DIRECTORY }}
          test-command: 'mvn -B -U clean compile test'

  # Deploy Test
  deploy-test-bike-boxes:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    environment: test
    needs: test
    concurrency: deploy-test-bike-boxes
    env:
      KEYCLOAK_URL: https://auth.opendatahub.testingmachine.eu
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Create .env file
        uses: noi-techpark/github-actions/env-file@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          # General deployment options
          X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
          X_DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          X_DOCKER_TAG: ${{ env.DOCKER_TAG }}
          X_JAVA_OPTIONS: -Xms128m -Xmx512m

          # Open Data Hub Writer Connectivity
          X_OAUTH_AUTH_URI: ${{ env.KEYCLOAK_URL }}/auth
          X_OAUTH_TOKEN_URI: ${{ env.KEYCLOAK_URL }}/auth/realms/noi/protocol/openid-connect/token
          X_OAUTH_CLIENT_ID: odh-mobility-datacollector
          X_OAUTH_CLIENT_NAME: odh-mobility-datacollector
          X_OAUTH_CLIENT_SECRET: ${{ secrets.DATACOLLECTORS_CLIENT_SECRET_TEST }}
          X_OAUTH_BASE_URI: https://mobility.share.opendatahub.testingmachine.eu/json

          # Data writer settings
          X_ODH_CLIENT_PROVENANCE_NAME: ${{ env.PROJECT_NAME }}
          X_ODH_CLIENT_PROVENANCE_VERSION: ${{ github.sha }}
          X_ODH_CLIENT_PROVENANCE_ORIGIN: ${{ env.ODH_ORIGIN }}
          X_ODH_CLIENT_STATIONTYPE: ${{ env.ODH_STATIONTYPE}}
          X_ODH_CLIENT_STATIONBAYTYPE: ${{ env.ODH_STATIONBAYTYPE}}
          X_ODH_CLIENT_PERIOD: ${{ env.ODH_PERIOD }}

          # Bike boxes api endpoint configuration
          X_ENDPOINT_OAUTH_URI: ${{ secrets.BIKE_BOXES_OAUTH_URI }} 
          X_ENDPOINT_OAUTH_CLIENT_ID: ${{ secrets.BIKE_BOXES_OAUTH_CLIENT_ID }}
          X_ENDPOINT_OAUTH_CLIENT_SECRET: ${{ secrets.BIKE_BOXES_OAUTH_CLIENT_SECRET }} 
          X_ENDPOINT_URI: ${{ vars.BIKE_BOXES_ENDPOINT_URI }}

          # Logging
          X_LOG_LEVEL: info
          X_LOG_STYLE: json

          # Task scheduler
          X_SCHEDULER_CRON: "* */10 * * * *"
          X_SCHEDULER_POOL_SIZE: 1

      - name: Build project
        uses: noi-techpark/github-actions/maven-build@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
          java-version: ${{ env.JAVA_VERSION }}
          build-command: 'mvn -B -DskipTests -DfinalName=ROOT clean package'

      - name: Build and push images
        uses: noi-techpark/github-actions/docker-build-and-push@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}


      - name: Deploy application
        uses: noi-techpark/github-actions/docker-deploy@v2
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure/ansible
          hosts: 'test'
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          docker-username: 'noi-techpark-bot'
          docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          project-name: ${{ env.PROJECT_NAME }}

# Deploy Production
#  deploy-prod-bike-boxes:
#    runs-on: ubuntu-20.04
#    if: github.ref == 'refs/heads/prod'
#    needs: test
#    concurrency: deploy-prod-bike-boxes
#    env:
#      KEYCLOAK_URL: https://auth.opendatahub.com
#    steps:
#      - name: Checkout source code
#        uses: actions/checkout@v2
#      - name: Create .env file
#        uses: noi-techpark/github-actions/env-file@v2
#        with:
#          working-directory: ${{ env.WORKING_DIRECTORY }}
#        env:
#          # General deployment options
#          X_COMPOSE_PROJECT_NAME: ${{ env.PROJECT_NAME }}
#          X_DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
#          X_DOCKER_TAG: ${{ env.DOCKER_TAG }}
#          X_JAVA_OPTIONS: -Xms128m -Xmx512m
#
#          # Open Data Hub Writer Connectivity
#          X_authorizationUri: ${{ env.KEYCLOAK_URL }}/auth
#          X_tokenUri: ${{ env.KEYCLOAK_URL }}/auth/realms/noi/protocol/openid-connect/token
#          X_clientId: odh-mobility-datacollector
#          X_clientName: odh-mobility-datacollector
#          X_clientSecret: ${{ secrets.DATACOLLECTORS_CLIENT_SECRET_PROD }}
#          X_scope: openid
#          X_BASE_URI: https://mobility.share.opendatahub.bz.it/json
#
#          X_ENDPOINT_OAUTH_URI: ${{ secrets.BIKE_BOXES_OAUTH_URI }} 
#          X_ENDPOINT_OAUTH_CLIENT_ID: ${{ secrets.BIKE_BOXES_OAUTH_CLIENT_ID }}
#          X_ENDPOINT_OAUTH_CLIENT_SECRET: ${{ secrets.BIKE_BOXES_OAUTH_CLIENT_SECRET }} 
#
#          X_ENDPOINT_URI: ${{ env.BIKE_BOXES_ENDPOINT_URI}}
#
#          # Logging
#          X_LOG_LEVEL: info
#          X_LOG_STYLE: json
#
#          X_provenance_name: ${{ env.PROJECT_NAME }}
#          X_provenance_version: ${{ github.sha }}
#
#          # TODO: Add your env vars here, prefixed with X_
#          X_SCHEDULER_CRON: "* */10 * * * *"
#          X_SCHEDULER_POOL_SIZE: 1
#
#
#      - name: Build project
#        uses: noi-techpark/github-actions/maven-build@v2
#        with:
#          working-directory: ${{ env.WORKING_DIRECTORY }}
#          java-version: ${{ env.JAVA_VERSION }}
#          build-command: 'mvn -B -DskipTests -DfinalName=ROOT clean package'
#
#      - name: Build and push images
#        uses: noi-techpark/github-actions/docker-build-and-push@v2
#        with:
#          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure
#          docker-username: ${{ github.actor }}
#          docker-password: ${{ secrets.GITHUB_TOKEN }}
#
#
#      - name: Deploy application
#        uses: noi-techpark/github-actions/docker-deploy@v2
#        with:
#          working-directory: ${{ env.WORKING_DIRECTORY }}/infrastructure/ansible
#          hosts: 'prod'
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#          docker-username: 'noi-techpark-bot'
#          docker-password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
#          project-name: ${{ env.PROJECT_NAME }}

